### PR TITLE
Implemented comment scraping #11

### PR DESCRIPTION
**Pull request by yu-lily**
Kernel dies on windows, should work on other platforms

### CODE REVIEW

**Comment by brianjhuang** [comment]
Hey Lily, 

It looks like it works fine for Linux, so I also imagine it works fine for Mac OS.

Couple notes :
    -  Let's possibly move the file path to data/raw/Reddit. Minor nitpick
    -  Can we get the main text of the Reddit post as well?
    -  This is less of a code issue but looks like a lot of economy talk is about geopolitics... wonder if that will create an issue later on.

**Review by brianjhuang — CHANGES_REQUESTED** [review]
- Add the ability to download Reddit Post Content
- Is upvotes/Downvotes possible?

**Comment by yu-lily** [comment]
Added scraping of main text of posts, output schema now has column to specify post/comment.

Also included refactor of notebook #12

**Review by brianjhuang — APPROVED** [review]
lgtm!

**Pull request merged**
